language: go
go:
  - 1.10.x
install:
  - go get github.com/kkragenbrink/slate
  - go get -v .
  - go get -v github.com/golang/lint/golint
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
