[metadata.heroku]
  root-package = "github.com/kkragenbrink/slate"
  ensure = true

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "6.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/heroku/x"
  version = "0.0.1"

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.19.0"
