[metadata.heroku]
  root-package = "github.com/kkragenbrink/slate"
  ensure = true

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"